name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        coverage: [false]
        include:
          - python-version: 3.7
            coverage: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -U pytest pytest-cov
    - name: Run tests
      if: matrix.coverage == false
      run: |
        echo "tests ${{ matrix.python-version }}" > artifact-${{ matrix.python-version }}.txt
    - name: Coverage tests
      if: matrix.coverage
      run: echo "coverage tests"
    - name: Test artifact
      if: matrix.coverage == false
      uses: actions/upload-artifact@v2
      with:
        name: Artifact ${{ matrix.python-version }}
        path: artifact*.txt
